import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import { toast } from 'sonner';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle, Table, TableRow, TableCell, WidthType } from 'docx';

interface ExportOptions {
  summaryCardRef: React.RefObject<HTMLDivElement>;
  nativeName: string;
  language: 'en' | 'hi';
  onProgress?: (stage: string) => void;
}

export interface BusinessWordExportData {
  nativeName: string;
  businessScore: number;
  businessSuitability: string;
  tenthHouseSign: string;
  tenthHouseLord: string;
  seventhHouseSign: string;
  activeSoleYogsCount: number;
  activePartnershipYogsCount: number;
  activeFieldYogsCount: number;
  topBusinessFields: string[];
  businessTiming: string;
  partnershipCompatibility: string;
  financialPotential: string;
  riskTolerance: string;
  planetsIn10th: string[];
  planetsIn7th: string[];
  soleYogs: Array<{ name: string; description: string }>;
  partnershipYogs: Array<{ name: string; description: string }>;
  fieldYogs: Array<{ name: string; fields: string[] }>;
  remedies: Array<{ planet: string; mantra: string; donation: string }>;
}

const getText = (en: string, hi: string, lang: 'en' | 'hi') => lang === 'hi' ? hi : en;

export const exportBusinessPDF = async ({
  summaryCardRef,
  nativeName,
  language,
  onProgress,
}: ExportOptions): Promise<boolean> => {
  try {
    if (!summaryCardRef.current) {
      toast.error(getText('Card not found', 'कार्ड नहीं मिला', language));
      return false;
    }

    onProgress?.(getText('Capturing Business Summary...', 'व्यापार सारांश कैप्चर हो रहा है...', language));
    
    const summaryCanvas = await html2canvas(summaryCardRef.current, {
      scale: 2.5,
      useCORS: true,
      logging: false,
      backgroundColor: '#ffffff',
    });

    onProgress?.(getText('Generating PDF...', 'PDF बना रहे हैं...', language));

    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    const pageWidth = 210;
    const pageHeight = 297;
    const margin = 10;
    const contentWidth = pageWidth - (margin * 2);

    // --- Cover Page ---
    pdf.setFillColor(88, 28, 135); // Purple
    pdf.rect(0, 0, pageWidth, pageHeight, 'F');
    
    // Decorative border
    pdf.setDrawColor(255, 215, 0); // Gold
    pdf.setLineWidth(1);
    pdf.rect(margin, margin, contentWidth, pageHeight - (margin * 2), 'S');
    pdf.rect(margin + 3, margin + 3, contentWidth - 6, pageHeight - (margin * 2) - 6, 'S');

    // Title
    pdf.setTextColor(255, 215, 0);
    pdf.setFontSize(28);
    pdf.setFont('helvetica', 'bold');
    const title = getText('COMPLETE BUSINESS REPORT', 'संपूर्ण व्यापार रिपोर्ट', language);
    pdf.text(title, pageWidth / 2, 60, { align: 'center' });

    // Subtitle
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'normal');
    const subtitle = getText("Based on R.G. Rao's Bhrighu Nandi Nadi", "R.G. राव की भृगु नंदी नाड़ी पर आधारित", language);
    pdf.text(subtitle, pageWidth / 2, 75, { align: 'center' });

    // Decorative symbol
    pdf.setFontSize(40);
    pdf.text('🏢', pageWidth / 2, 110, { align: 'center' });

    // Native Name
    pdf.setFontSize(18);
    pdf.setFont('helvetica', 'bold');
    pdf.text(getText('Prepared for:', 'के लिए तैयार:', language), pageWidth / 2, 145, { align: 'center' });
    pdf.setTextColor(255, 215, 0);
    pdf.setFontSize(24);
    pdf.text(nativeName, pageWidth / 2, 160, { align: 'center' });

    // Date
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(12);
    const dateStr = new Date().toLocaleDateString(language === 'hi' ? 'hi-IN' : 'en-IN', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
    pdf.text(dateStr, pageWidth / 2, 180, { align: 'center' });

    // Contents
    pdf.setFontSize(14);
    pdf.text(getText('Report Contents:', 'रिपोर्ट विषय:', language), pageWidth / 2, 210, { align: 'center' });
    
    pdf.setFontSize(11);
    const contents = language === 'hi' 
      ? ['1. व्यापार प्रोफ़ाइल सारांश', '2. व्यापार प्रकार विश्लेषण', '3. व्यापार क्षेत्र योग', '4. साझेदारी विश्लेषण', '5. व्यापार समय और चक्र', '6. व्यापार उपाय']
      : ['1. Business Profile Summary', '2. Business Type Analysis', '3. Business Field Yogs', '4. Partnership Analysis', '5. Business Timing & Cycles', '6. Business Remedies'];
    
    contents.forEach((item, idx) => {
      pdf.text(item, pageWidth / 2, 225 + (idx * 8), { align: 'center' });
    });

    // Footer
    pdf.setFontSize(9);
    pdf.setTextColor(180, 180, 180);
    pdf.text(getText('Generated by Jyoti Stellar Compass', 'ज्योति स्टेलर कम्पास द्वारा निर्मित', language), pageWidth / 2, pageHeight - 20, { align: 'center' });

    // --- Page 2: Business Summary Card ---
    pdf.addPage();
    
    // Page header
    pdf.setFillColor(88, 28, 135); // Purple
    pdf.rect(0, 0, pageWidth, 25, 'F');
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.text(getText('Business Profile Summary', 'व्यापार प्रोफ़ाइल सारांश', language), pageWidth / 2, 16, { align: 'center' });
    
    // Add summary card image
    const summaryImgData = summaryCanvas.toDataURL('image/png');
    const summaryImgHeight = (summaryCanvas.height * contentWidth) / summaryCanvas.width;
    
    const maxHeight = pageHeight - 40;
    const finalSummaryHeight = Math.min(summaryImgHeight, maxHeight);
    const finalSummaryWidth = (finalSummaryHeight / summaryImgHeight) * contentWidth;
    
    pdf.addImage(
      summaryImgData, 
      'PNG', 
      (pageWidth - finalSummaryWidth) / 2, 
      30, 
      finalSummaryWidth, 
      finalSummaryHeight
    );

    // --- Final Page: Disclaimer ---
    pdf.addPage();
    
    pdf.setFillColor(248, 250, 252);
    pdf.rect(0, 0, pageWidth, pageHeight, 'F');
    
    pdf.setTextColor(30, 41, 59);
    pdf.setFontSize(16);
    pdf.setFont('helvetica', 'bold');
    pdf.text(getText('Important Notes', 'महत्वपूर्ण टिप्पणियाँ', language), pageWidth / 2, 40, { align: 'center' });
    
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    
    const disclaimerEn = [
      '• This report is generated based on Vedic astrology principles using',
      "  R.G. Rao's Bhrighu Nandi Nadi methodology.",
      '',
      '• The predictions and recommendations are for guidance purposes only.',
      '  They should not be considered as absolute or deterministic.',
      '',
      '• Business success depends on multiple factors including your efforts,',
      '  market conditions, partnerships, and divine grace.',
      '',
      '• For personalized and comprehensive guidance, please consult a',
      '  qualified Vedic astrologer and business advisor.',
      '',
      '• The remedies suggested are traditional Vedic practices. Please follow',
      '  them with faith and consistency for best results.',
    ];
    
    const disclaimerHi = [
      '• यह रिपोर्ट R.G. राव की भृगु नंदी नाड़ी पद्धति का उपयोग करते हुए',
      '  वैदिक ज्योतिष सिद्धांतों पर आधारित है।',
      '',
      '• भविष्यवाणियाँ और सिफारिशें केवल मार्गदर्शन उद्देश्यों के लिए हैं।',
      '  इन्हें निरपेक्ष या निर्धारित नहीं माना जाना चाहिए।',
      '',
      '• व्यापार की सफलता आपके प्रयासों, बाजार की स्थितियों,',
      '  साझेदारी और दैवी कृपा सहित कई कारकों पर निर्भर करती है।',
      '',
      '• व्यक्तिगत और व्यापक मार्गदर्शन के लिए, कृपया किसी योग्य',
      '  वैदिक ज्योतिषी और व्यापार सलाहकार से परामर्श करें।',
      '',
      '• सुझाए गए उपाय पारंपरिक वैदिक प्रथाएं हैं। सर्वोत्तम परिणामों के लिए',
      '  कृपया इनका श्रद्धा और निरंतरता से पालन करें।',
    ];

    const disclaimer = language === 'hi' ? disclaimerHi : disclaimerEn;
    disclaimer.forEach((line, idx) => {
      pdf.text(line, margin + 10, 60 + (idx * 7));
    });

    // Thank you message
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(88, 28, 135);
    pdf.text(getText('Thank you for using Jyoti Stellar Compass!', 'ज्योति स्टेलर कम्पास का उपयोग करने के लिए धन्यवाद!', language), pageWidth / 2, 180, { align: 'center' });

    pdf.setFontSize(10);
    pdf.setTextColor(100, 116, 139);
    pdf.setFont('helvetica', 'normal');
    pdf.text('🏢 ' + getText('May your business ventures prosper!', 'आपके व्यापार उद्यम समृद्ध हों!', language), pageWidth / 2, 195, { align: 'center' });

    // Page numbers
    const totalPages = pdf.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      pdf.setPage(i);
      pdf.setFontSize(8);
      pdf.setTextColor(150, 150, 150);
      pdf.text(`${getText('Page', 'पृष्ठ', language)} ${i} / ${totalPages}`, pageWidth / 2, pageHeight - 8, { align: 'center' });
    }

    pdf.save(`Complete_Business_Report_${nativeName.replace(/\s+/g, '_')}.pdf`);
    
    return true;
  } catch (error) {
    console.error('Business PDF export error:', error);
    return false;
  }
};

export const printBusinessReport = (
  summaryCardRef: React.RefObject<HTMLDivElement>,
  language: 'en' | 'hi'
) => {
  if (!summaryCardRef.current) {
    toast.error(getText('Card not found', 'कार्ड नहीं मिला', language));
    return;
  }

  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(`
      <html>
        <head>
          <title>${getText('Complete Business Report', 'संपूर्ण व्यापार रिपोर्ट', language)}</title>
          <style>
            @import url('https://fonts.googleapis.com/css2?family=Noto+Serif+Devanagari:wght@400;600&display=swap');
            @page { margin: 15mm; }
            body { 
              font-family: system-ui, 'Noto Serif Devanagari', sans-serif; 
              margin: 0; 
              padding: 0;
              background: white;
            }
            * { color: black !important; }
            .page-break { page-break-after: always; }
            .cover {
              text-align: center;
              padding: 60px 20px;
              background: linear-gradient(135deg, #581c87 0%, #7c3aed 100%);
              color: white !important;
              min-height: 80vh;
              display: flex;
              flex-direction: column;
              justify-content: center;
              align-items: center;
            }
            .cover * { color: white !important; }
            .cover h1 { font-size: 28px; color: #ffd700 !important; margin-bottom: 10px; }
            .cover h2 { font-size: 16px; opacity: 0.9; }
            .cover .symbol { font-size: 48px; margin: 30px 0; }
            .cover .name { font-size: 24px; color: #ffd700 !important; margin-top: 20px; }
            .section { margin: 20px 0; }
            .section-title { 
              background: #581c87; 
              color: white !important; 
              padding: 12px 20px; 
              font-size: 16px; 
              font-weight: bold;
              margin-bottom: 20px;
            }
            .card { 
              max-width: 100%; 
              border: 1px solid #e2e8f0;
              border-radius: 12px;
              padding: 20px;
              margin-bottom: 20px;
            }
          </style>
        </head>
        <body>
          <div class="cover">
            <h1>${getText('COMPLETE BUSINESS REPORT', 'संपूर्ण व्यापार रिपोर्ट', language)}</h1>
            <h2>${getText("Based on R.G. Rao's Bhrighu Nandi Nadi", "R.G. राव की भृगु नंदी नाड़ी पर आधारित", language)}</h2>
            <div class="symbol">🏢</div>
            <p>${getText('Generated on:', 'निर्माण तिथि:', language)} ${new Date().toLocaleDateString(language === 'hi' ? 'hi-IN' : 'en-IN')}</p>
          </div>
          
          <div class="page-break"></div>
          
          <div class="section">
            <div class="section-title">${getText('Business Profile Summary', 'व्यापार प्रोफ़ाइल सारांश', language)}</div>
            <div class="card">${summaryCardRef.current.outerHTML}</div>
          </div>
        </body>
      </html>
    `);
    printWindow.document.close();
    setTimeout(() => printWindow.print(), 500);
  }
};

// Word Document Export
export const exportBusinessWord = async (
  data: BusinessWordExportData,
  language: 'en' | 'hi'
): Promise<boolean> => {
  try {
    const t = (en: string, hi: string) => language === 'hi' ? hi : en;
    
    const createSectionHeader = (text: string) => new Paragraph({
      children: [
        new TextRun({
          text: text,
          bold: true,
          size: 28,
          color: '581c87',
        }),
      ],
      heading: HeadingLevel.HEADING_1,
      spacing: { before: 400, after: 200 },
      border: {
        bottom: { style: BorderStyle.SINGLE, size: 6, color: '7c3aed' },
      },
    });

    const createSubHeader = (text: string) => new Paragraph({
      children: [
        new TextRun({
          text: text,
          bold: true,
          size: 24,
          color: '059669',
        }),
      ],
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 300, after: 150 },
    });

    const createLabelValue = (label: string, value: string) => new Paragraph({
      children: [
        new TextRun({ text: `${label}: `, bold: true, size: 22 }),
        new TextRun({ text: value, size: 22 }),
      ],
      spacing: { before: 80, after: 80 },
    });

    const createBulletPoint = (text: string) => new Paragraph({
      children: [new TextRun({ text: `• ${text}`, size: 22 })],
      spacing: { before: 60, after: 60 },
      indent: { left: 360 },
    });

    const doc = new Document({
      sections: [{
        properties: {},
        children: [
          // Title
          new Paragraph({
            children: [
              new TextRun({
                text: t('COMPLETE BUSINESS REPORT', 'संपूर्ण व्यापार रिपोर्ट'),
                bold: true,
                size: 40,
                color: '581c87',
              }),
            ],
            alignment: AlignmentType.CENTER,
            spacing: { after: 200 },
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: t("Based on R.G. Rao's Bhrighu Nandi Nadi", "R.G. राव की भृगु नंदी नाड़ी पर आधारित"),
                size: 22,
                italics: true,
                color: '6b7280',
              }),
            ],
            alignment: AlignmentType.CENTER,
            spacing: { after: 400 },
          }),
          new Paragraph({
            children: [
              new TextRun({ text: t('Prepared for: ', 'के लिए तैयार: '), size: 24 }),
              new TextRun({ text: data.nativeName, bold: true, size: 28, color: '581c87' }),
            ],
            alignment: AlignmentType.CENTER,
            spacing: { after: 600 },
          }),

          // Business Profile Section
          createSectionHeader(t('Business Profile', 'व्यापार प्रोफ़ाइल')),
          createLabelValue(t('Business Score', 'व्यापार स्कोर'), `${data.businessScore}/100`),
          createLabelValue(t('Recommended Type', 'अनुशंसित प्रकार'), data.businessSuitability),
          createLabelValue(t('Financial Potential', 'वित्तीय संभावना'), data.financialPotential),
          createLabelValue(t('Risk Profile', 'जोखिम प्रोफ़ाइल'), data.riskTolerance),
          createLabelValue(t('Business Timing', 'व्यापार समय'), data.businessTiming),

          // House Analysis
          createSectionHeader(t('House Analysis', 'भाव विश्लेषण')),
          createLabelValue(t('10th House (Karma)', '10वां भाव (कर्म)'), `${data.tenthHouseSign} - Lord: ${data.tenthHouseLord}`),
          createLabelValue(t('Planets in 10th', '10वें भाव में ग्रह'), data.planetsIn10th.length > 0 ? data.planetsIn10th.join(', ') : t('None', 'कोई नहीं')),
          createLabelValue(t('7th House (Partnership)', '7वां भाव (साझेदारी)'), data.seventhHouseSign),
          createLabelValue(t('Planets in 7th', '7वें भाव में ग्रह'), data.planetsIn7th.length > 0 ? data.planetsIn7th.join(', ') : t('None', 'कोई नहीं')),
          new Paragraph({
            children: [new TextRun({ text: '\n' + data.partnershipCompatibility, size: 22 })],
            spacing: { before: 100, after: 200 },
          }),

          // Yog Summary
          createSectionHeader(t('Business Yog Summary', 'व्यापार योग सारांश')),
          createLabelValue(t('Sole Proprietorship Yogs', 'एकल स्वामित्व योग'), `${data.activeSoleYogsCount} ${t('Active', 'सक्रिय')}`),
          createLabelValue(t('Partnership Yogs', 'साझेदारी योग'), `${data.activePartnershipYogsCount} ${t('Active', 'सक्रिय')}`),
          createLabelValue(t('Business Field Yogs', 'व्यापार क्षेत्र योग'), `${data.activeFieldYogsCount} ${t('Active', 'सक्रिय')}`),

          // Top Business Fields
          createSubHeader(t('Recommended Industries', 'अनुशंसित उद्योग')),
          ...data.topBusinessFields.map(field => createBulletPoint(field)),

          // Active Yogs Details
          ...(data.soleYogs.length > 0 ? [
            createSubHeader(t('Active Sole Proprietorship Yogs', 'सक्रिय एकल स्वामित्व योग')),
            ...data.soleYogs.flatMap(yog => [
              new Paragraph({
                children: [new TextRun({ text: `✓ ${yog.name}`, bold: true, size: 22, color: 'f97316' })],
                spacing: { before: 100 },
              }),
              new Paragraph({
                children: [new TextRun({ text: yog.description, size: 20, italics: true })],
                spacing: { after: 100 },
                indent: { left: 360 },
              }),
            ]),
          ] : []),

          ...(data.partnershipYogs.length > 0 ? [
            createSubHeader(t('Active Partnership Yogs', 'सक्रिय साझेदारी योग')),
            ...data.partnershipYogs.flatMap(yog => [
              new Paragraph({
                children: [new TextRun({ text: `✓ ${yog.name}`, bold: true, size: 22, color: '3b82f6' })],
                spacing: { before: 100 },
              }),
              new Paragraph({
                children: [new TextRun({ text: yog.description, size: 20, italics: true })],
                spacing: { after: 100 },
                indent: { left: 360 },
              }),
            ]),
          ] : []),

          // Remedies
          ...(data.remedies.length > 0 ? [
            createSectionHeader(t('Business Remedies', 'व्यापार उपाय')),
            ...data.remedies.flatMap(remedy => [
              new Paragraph({
                children: [new TextRun({ text: `${remedy.planet}`, bold: true, size: 24, color: '059669' })],
                spacing: { before: 200 },
              }),
              createLabelValue(t('Beej Mantra', 'बीज मंत्र'), remedy.mantra),
              createLabelValue(t('Donation', 'दान'), remedy.donation),
            ]),
          ] : []),

          // Disclaimer
          new Paragraph({
            children: [new TextRun({ text: '\n\n' })],
          }),
          createSectionHeader(t('Important Notes', 'महत्वपूर्ण टिप्पणियाँ')),
          new Paragraph({
            children: [
              new TextRun({
                text: t(
                  'This report is based on Vedic astrology principles and should be used for guidance only. Business success depends on multiple factors including efforts, market conditions, and divine grace. Please consult qualified professionals for important business decisions.',
                  'यह रिपोर्ट वैदिक ज्योतिष सिद्धांतों पर आधारित है और केवल मार्गदर्शन के लिए उपयोग की जानी चाहिए। व्यापार की सफलता प्रयासों, बाजार की स्थितियों और दैवी कृपा सहित कई कारकों पर निर्भर करती है। महत्वपूर्ण व्यापार निर्णयों के लिए कृपया योग्य पेशेवरों से परामर्श करें।'
                ),
                size: 20,
                italics: true,
                color: '6b7280',
              }),
            ],
            spacing: { before: 200, after: 400 },
          }),

          // Footer
          new Paragraph({
            children: [
              new TextRun({
                text: t('Generated by Jyoti Stellar Compass', 'ज्योति स्टेलर कम्पास द्वारा निर्मित'),
                size: 18,
                color: '9ca3af',
              }),
              new TextRun({ text: ' | ' }),
              new TextRun({
                text: new Date().toLocaleDateString(language === 'hi' ? 'hi-IN' : 'en-IN'),
                size: 18,
                color: '9ca3af',
              }),
            ],
            alignment: AlignmentType.CENTER,
            spacing: { before: 400 },
          }),
        ],
      }],
    });

    const blob = await Packer.toBlob(doc);
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Complete_Business_Report_${data.nativeName.replace(/\s+/g, '_')}.docx`;
    link.click();
    URL.revokeObjectURL(url);

    return true;
  } catch (error) {
    console.error('Word export error:', error);
    return false;
  }
};

export type { ExportOptions };
